// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OrganizationRegister.Store.CodeFirst.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterVarcharColumnsToText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterVarcharColumnsToText));
        
        string IMigrationMetadata.Id
        {
            get { return "201512220717510_AlterVarcharColumnsToText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
