// <auto-generated />
namespace OrganizationRegister.Store.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCallChargeType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCallChargeType));
        
        string IMigrationMetadata.Id
        {
            get { return "201608260816179_AddCallChargeType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
