// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OrganizationRegister.AcceptanceTests.Features.Organization
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UpdatingOrganizationContactInformationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdatingOrganizationContactInformation.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UpdatingOrganizationContactInformation", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "UpdatingOrganizationContactInformation")))
            {
                OrganizationRegister.AcceptanceTests.Features.Organization.UpdatingOrganizationContactInformationFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("there is an organization", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting organization contact information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingOrganizationContactInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting organization contact information", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table1.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 7
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table2.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 10
 testRunner.Then("the organization has the following contact information:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting organization contact information again")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingOrganizationContactInformationAgain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting organization contact information again", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table3.AddRow(new string[] {
                        "0100100",
                        "Muu",
                        "Charge Info",
                        "info@affecto.com",
                        "Finland",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Everyone",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 15
 testRunner.Given("the following contact information is set to the organization:", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table4.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 18
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table5.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 21
 testRunner.Then("the organization has the following contact information:", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Organization can have no contact information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void OrganizationCanHaveNoContactInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Organization can have no contact information", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table6.AddRow(new string[] {
                        "0100100",
                        "Muu",
                        "Charge Info",
                        "info@affecto.com",
                        "Finland",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Everyone",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 27
 testRunner.Given("the following contact information is set to the organization:", ((string)(null)), table6, "Given ");
#line 30
 testRunner.When("contact information of the organization is set as empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
 testRunner.Then("the organization has no contact information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid email address")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidEmailAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid email address", ((string[])(null)));
#line 33
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table7.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi2affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 34
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table7, "When ");
#line 37
 testRunner.When("contact information of the organization is set as empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid phone number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidPhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid phone number", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table8.AddRow(new string[] {
                        "Muu",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 41
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table8, "When ");
#line 44
 testRunner.When("contact information of the organization is set as empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid web address")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidWebAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid web address", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table9.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www,affecto,com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url.sv"});
#line 48
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table9, "When ");
#line 51
 testRunner.When("contact information of the organization is set as empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid homepage url")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidHomepageUrl()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid homepage url", ((string[])(null)));
#line 54
 this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call charge type",
                        "Phone call charge info",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type",
                        "homepage in finnish",
                        "homepage in swedish"});
            table10.AddRow(new string[] {
                        "0205 777 450",
                        "Muu",
                        "Charge Info",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu",
                        "http://wwww.url.fi",
                        "http://wwww.url"});
#line 55
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table10, "When ");
#line 58
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
